---
title:  Biol/Math 218 Portfolio 1
subtitle: Introduction to samples and data
author: Your Name Here
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    downcute_theme: "chaos"
    toc_depth: 3
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../html"
    )
  })
---

## Introduction

In this first portfolio, you will demonstrate your knowledge of the basics of sampling 
and data types. Answers to each **question** should be entered in the designated `Answer:` block. 
All **exercises** need to be done within `r{}` chunks, with any 
non-code commented out with **#**.

- Total exercises: **01**
- Total questions: **13**

## Part 01: Samples

An Environmental Studies student was interested in the attitudes of students at her college about 
new sustainability practices at the school. She developed a questionnaire and acquired the 
list of emails for all enrolled students. She randomly selected 500 students 
from those email lists to send her questionnaire.

A total of 150 of the 500 questionnaires were filled out and returned to her.

**Question 01**: Define and contrast samples and populations, and parameters and estimates

`Q01 Answer:`

**Question 02**: Can the 150 students that returned questionnaires be considered 
as a random sample of all students? Why or why not?

`Q02 Answer:`

**Question 03**: Explain what type of bias might be at play here.

`Q03 Answer:`

**Question 04**: What is sampling error and how can researchers can minimize it?

`Q04 Answer:`

## Part 02: Data types

Here are some vectors of data
```{r, example_data}
y1 <- iris$Sepal.Length
y2 <- Orange$age
y3 <- Orange$circumference
y4 <- InsectSprays$count
y5 <- ChickWeight$ Weight
# ALl of these are built-in data in R
# Explore more by running
# data()
```

### Exercise 01
Reproduce the code `example_data` chunk below and mark each vector as 
either **continuous** or **discrete** using comments, "#". Make sure to give your new
chunk a unique title (I suggest something like `exercise_01`).

## Part 03: Parameters *vs* estimates

Measuring biodiversity, the number and type of animals and plants in a given area is
important for informing conservation efforts. To determine the community composition
of pollinators in parks in New York City, a researcher placed hundreds of red cup traps
filled with water around the city to attract and trap pollinators in the summer of 2019. 
Each cup was checked daily for insects and the water was refilled. The collected
pollinators were pinned and identified in the lab. At the end of the study,
the total number of pollinator species (richness) in New York City parks were estimated by
the total number of pollinators collected during the study. 

**Question 05**: What parameter is being estimated in this pollinator study?

`Q05 Answer:`

**Question 06**: Is the sample of individuals captured in red cup traps 
likely to be a random sample? Why or why not? Include the two criteria 
that define a sample as random in your answer.

`Q06 Answer:`

**Question 07**: Is the number of species in the sample likely to be an 
unbiased estimate? Why or why not?

`Q07 Answer:`

## Part 4: Explanatory *vs* response variables

The courtship of male and female fruit flies is complex and can be
impacted by changes in their environment. A scientist exposed thirty
male fruit flies to the pesticide Paraquat, which can inhibit neurological
function, as well as kept thirty males unexposed. She studied whether 
mating success was different between the two groups.

**Question 08**: Which is the explanatory and which is the response variable?

`Q08 Answer:`

**Question 09**: For each variable, state whether they are categorical or numeric?

`Q09 Answer:`

**Question 10**: Is this study observational or experimental?

`Q10 Answer:`

A researcher wanted to compare aquatic insect size in urban and 
rural streams in upstate New York. The collected individuals of
the hellgrammite *Nigronia serricornus* in both an urban and
rural stream sites and weighed them in the lab.

**Question 11**: Which is the explanatory and which is the response variable?

`Q11 Answer:`

**Question 12**: Which variables are categorical and which are numeric?

`Q12 Answer:`

**Question 13**: Is this study observational or experimental?

`Q13 Answer:`





















