---
title:  Biol/Math 218 Portfolio 7
subtitle: Binomial test and chi squared test
author: Your Name Here
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    downcute_theme: "chaos"
    toc_depth: 3
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "/knit_portfolio"
    )
  })
---

## Introduction 
In this portfolio, you will demonstrate your skills using the binomial and chi squared tests. 
Answers to each **question** should be entered in the 
designated `Answer:` block. All **exercises** need to be done within `r{}` chunks, with any 
non-code commented out with `#`. Use the `print()` function to show results of calculations.


- Total exercises: **07**
- Total questions: **00**

## Part 01: Binomial test

Researchers proposed that the length of the tail feathers of male long-tailed widowbirds
is selected on by female widowbirds even though longer tails make it more difficult for the 
males to fly. They postulated that males with longer tail feathers
would be more likely to successfully find a mate. To test this, 20 male birds were given 
"tail extensions" to make their tails significantly longer. Another 20 males were left with their
tails at their natural length. Pairs of males with and without tail extensions and the choice
of males the female made was recorded (N = 20 pairs). In 18 of the 20 pairs, the male with 
the extension was chosen over the male without. 

### Exercise 01
With these data test whether the males with tail extensions and those lacking
the extension are equally likely to be chosen by a female. 

Make sure to include:
1) Hypotheses (commented)
2) Binomial equation and calculation
3) Decision (commented)


### Exercise 02 
For the above data, calculate a 95% confidence interval 


### Exercise 03
Check your answers for the two tasks above by using the `binom.test()` 
function.


## Part 02: Chi squared test

You are interested in a population of wild rabbits that exhibit either black or
white fur. The difference in fur is controlled by a single gene that has two alleles,
the white allele (b), and the black allele (B). Since rabbits are diploid (2N), each
individual has two alleles for the fur color gene. Individuals that have both black
fur alleles (BB) or at least one black fur allele (Bb or bB), have black fur. White
furred individuals have two copies of the white fur allele (bb).

All three genotypes exist in this population of rabbits and if having the white 
allele does not impact fitness (survival and reproduction), then individuals 
with 0, 1, or 2 copies of the "b" allele should follow a binomial distribution.

You investigate a population of 92 rabbits in the mountains of North Macedonia
and find that 52 were BB, 34 were Bb, and 6 were bb. Assume that this
is a random sample of rabbits.

### Exercise 04
Calculate the fraction of b alleles in the population 
(remember, each rabbit has two copies of the gene).


### Exercise 05
With your estimate of the fraction of b alleles, and assuming 
a binomial distribution, calculate the expected frequency of bears with 0, 1, and 2 copies.
Hint: This is the basis of Hardy-Weinberg Equilibrium)

### Exercise 06
Using the chi-square test, test the hypothesis: Does allele frequency of b follow a binomial
distribution? 

Make sure to include:
1) Hypotheses (commented) 
2) All calculations
3) P-value produced using the pchisq() function
4) Decision (commented)


### Exercise 07
Use the `chisq.test()` function to check your work above